### ISSUE TITLE
Add support for NVDA on Windows Store

### ISSUE THREAD

**Issue by josephsl** [josephsl/stationPlaylist#46]
Hi,

Applicable on Windows 10: as of NVDA 2018.1, foundation has been laid to allow submitting NVDA to Microsoft Store. As a converted desktop (Project Centennial) app, there are limitations, the biggest of which is inability to support add-ons. Even with this lifted, another limitation will be imposed: inability to update add-ons through the app, as extensions for apps are meant to be updated through Store app instead.

Thus prepare for a day when the add-on will run inside Windows Store version of NVDA. Specifically:

* Disable update checks if config.isAppX is true, as only Store-based update check will work. This is applicable for manual and automatic update checks, as well as restarting the update timer when profiles are switched.
* Disable update channel selection and update interval if running inside Windows Store NVDA.
* No broadcast profiles until running custom code inside add-on installer is approved. Without this, broadcast profile migration isn't possible.
* Check for encoder connection status every second instead of every millisecond in order to conserve battery power.

The first step is to find out what's different between regular and Windows Store versions of NVDA and adopt the add-on code accordingly. While doing this, consult Universal Windows Platform guidelines from Microsoft, as well as app extensions and their requirements and limitations. At the moment one can simulate Windows Store NVDA by either building the package or running a version of NVDA with Appx flag set. Running extensions for UWP apps require Windows 10 Version 1607 or later. This is being taken care of.

Next, modify the add-on source to fit the needs of Windows Store NVDA. The first and most noticeable change will be how add-on update management is performed. This is part of a larger project to restructure the update facility in order to minimize dependency on configuration module and vice versa, which is part of a larger work designed to make use of extension points. This should be done first not only because of Windows Store NVDA but also to react to a possible arrival of add-on update from NVDA.

Next comes other features such as encoder support. Once this is done, testing should be done, with the last step being user interface and documentation.

The entire project will take at least a month to complete (including follow-up tests). During this time, other work should be minimal unless critical bugs emerge. The end result should be an add-on (rather, an extension for the Windows Store NVDA) that works beautifully like it does now.

Thanks.

**Comment by gdata1** [comment]
Hello. is the NVDA package ready for the Windows store? If so can I download it?

**Comment by josephsl** [comment]
Hi, no and no – NVDA is not listed on Microsoft Store yet, and no, it isn’t possible to download this version at the moment. Sorry.

**Comment by gdata1** [comment]
Thanks. Know when it will be available?

**Comment by josephsl** [comment]
Hi, no. Thanks.

**Comment by josephsl** [comment]
Hi,

Closing for now - to be reopened once Store version actually ships.

Thanks.
